### ISSUE TITLE
Hello londonappbrewery

### ISSUE THREAD

**Issue by kadima101** [londonappbrewery/destini-challenge-starting#4]
https://github.com/londonappbrewery/destini-challenge-starting/blob/344c34cc66361611c77a5bb9f86921f2a5722215/lib/main.dart#L77

I thought it should be for choice 2 instead of choice 1:
//TODO: Step 14 - Use the storyBrain to get the text for **choice 1**.

**Comment by filipedfs** [comment]
Same here.

**Comment by TheMuellenator** [comment]
Thanks for raising this! I've updated the stub.
